### ISSUE TITLE
No verifications when completing the payment process

### ISSUE THREAD

**Issue by Zoddo** [Bee-Lab/BeelabPaypalBundle#1]
For exemple, call directly the return URL marks the transaction as complete without validation.

**Comment by garak** [comment]
That should be achieved by the call to ``completePurchase`` method on the gateway, inside ``Service`` class.

**Comment by Zoddo** [comment]
There is no verifications in your code :

https://github.com/Bee-Lab/BeelabPaypalBundle/blob/master/Paypal/Service.php#L91

**Comment by garak** [comment]
What kind of verification you need? To complete transaction, a user need to know the token, that is unlikely.

**Comment by Zoddo** [comment]
The token can be retrieved in the paypal URL when the user is redirected.

**Comment by garak** [comment]
Can you tell me the data you tried with?

Here are mine:
paypal URL: https://www.sandbox.paypal.com/it/cgi-bin/merchantpaymentweb?cmd=_flow&SESSION=HwZYDDek9uFb9yR304zQ6gEA-_H1y59maEo5mZ8a6keeOUhgafFfts3IRx8&dispatch=50a222a57771920b6a3d7b606239e4d529b525e0b7e69bf0224adecfb0124e9b61f737ba21b08198acc59b45c1b5383c3fbf91319c9514c0
transaction token: EC-5C41195852610802R

I can't find the token inside the URL

**Comment by Zoddo** [comment]
Check the network console in your browser:
![capture](https://cloud.githubusercontent.com/assets/5215545/7542087/7b606866-f5ba-11e4-982a-46e8b55ead8b.PNG)

1. My request (redirected to paypal)
2. The 1st request to paypal servers. The URL contain the token
3. The URL that you have mentioned

**Comment by garak** [comment]
Thank yous @Zoddo for your report. I released a new tag, including the fix. Feel free to open another issue, if you find other problems.
