### ISSUE TITLE
how to change from DEV to PROD?!

### ISSUE THREAD

**Issue by bacemhm** [Bee-Lab/BeelabPaypalBundle#15]

**Comment by garak** [comment]
Unfortunately this is an issue tracker, not a support page.
You can refer to Symfony documentation to get many forms of support.

**Comment by bacemhm** [comment]
i am in use this bundle in test and DEV mode work fine but when i change it to PROD i got that 
"Security header is not valid"

**Comment by garak** [comment]
Then your problem is not with this bundle, but with Paypal configuration

**Comment by bycrea** [comment]
Hi,
Same problem here, works fine in DEV env. but i get "The server returned a "503 Service Unavailable" in PROD env. Any ideas please?
