### ISSUE TITLE
service beelab_paypal.service not found

### ISSUE THREAD

**Issue by ankurilogix** [Bee-Lab/BeelabPaypalBundle#16]
i have to install beelab PayPal bundles symfony 4.2.2 but I have some issue facing,
please help me resolve my issue.

issue :
Cannot autowire argument $service of "App\Controller\DefaultController::payment()": it references class "Beelab\PaypalBundle\Paypal\Service" but no such service exists. You should maybe alias this class to the existing "beelab_paypal.service" service.

**Comment by garak** [comment]
Bundle version?

**Comment by ankurilogix** [comment]
> Bundle version?

1.4

**Comment by garak** [comment]
Try requiring `^1.4@dev`

**Comment by garak** [comment]
Closing for missing feedback. Hope you solved
