### ISSUE TITLE
Bug with guzzle

### ISSUE THREAD

**Issue by jokari4242** [Bee-Lab/BeelabPaypalBundle#2]
Hello and thanks for this bundle!

In production everythings it's ok, but when i'am in debug mode, i have this error when prepare payment : 

```
[curl] 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [url] https://api-3t.sandbox.paypal.com/nvp? ...
```

Do you have an idea?

Thanks!

**Comment by garak** [comment]
Looks like you're getting some problem with ssl handshake.
Try from your terminal:
```bash
 curl -v https://api-3t.sandbox.paypal.com/nvp
```

You should get a string starting with "ACK=Failure"

**Comment by jokari4242** [comment]
Thanks for your quickly anser!

```
ACK=Failure&L_ERRORCODE0=81002&L_SHORTMESSAGE0=Unspecified%20Method&L_LONGMESSAGE0=Method%20Specified%20is%20not%20Supported&L_SEVERITYCODE0=ErrorMacBook-Pro-de-Antoine-3:abcenligne antoineperso$ 
```

I have updated php recently, i need to activate extention in my php.ini ?

**Comment by garak** [comment]
Honestly, I don't know.
Anyway, it looks like your problem is not related to this bundle, but likely to your configuration (or maybe to guzzle).
Otherwise, feel free to open another issue
