### ISSUE TITLE
Can't install on Symfony 3.4.12

### ISSUE THREAD

**Issue by polnetwork** [Bee-Lab/BeelabPaypalBundle#5]
Hi, I'm trying to install on a Symfony 3.4.12 project and I'm getting this errors:

composer require beelab/paypal-bundle
Using version ^1.3 for beelab/paypal-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install beelab/paypal-bundle v1.3.1
    - Conclusion: remove doctrine/doctrine-bundle 1.8.1
    - Conclusion: don't install doctrine/doctrine-bundle 1.8.1
    - symfony/http-foundation v2.1.0 conflicts with doctrine/doctrine-bundle[1.8.1].
...

and a lot more like this las line.

What I'm doing bad?

Thank's for all.

**Comment by garak** [comment]
You need to execute `composer require php-http/guzzle6-adapter` before.
As alternative, you can require any package implementing [php-http/client-implementation](https://packagist.org/providers/php-http/client-implementation)

I'll update docs ASAP

**Comment by polnetwork** [comment]
Thank's I'll try it.
