### ISSUE TITLE
Service "beelab_paypal.service" not found

### ISSUE THREAD

**Issue by adib0u** [Bee-Lab/BeelabPaypalBundle#9]
Hello, I try to integrate my bundle to Symfony 4.

I have an error  in the in src/Controller/DefaultController.php (line 44) : 

$response =$this->get('beelab_paypal.service')->setTransaction($transaction)->start();

Service "beelab_paypal.service" not found: even though it exists in the app's container, the container inside "App\Controller\PaymentController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session" and "twig" services. Unless you need extra laziness, try using dependency injection instead. Otherwise, you need to declare it using "PaymentController::getSubscribedServices()".

It's look like Symfony can't find the service. 

Thank you for your answer :)

**Comment by garak** [comment]
I guess that you're following docs and using `$this->get('beelab_paypal.service')`.
Unfortunately, docs are not up to date, you can't get service from container like that in Symfony 4. You need to inject service in controller.

**Comment by garak** [comment]
Closing in favor of #10
